site_/site_/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('vote.urls'))
]

site_/vote/urls.py
from django.urls import path
from . views import index_vote,ShowAll, show_detail, ShowDetail
app_name = "vote"
urlpatterns = [
    path('', index_vote, name='index' ),
    path('questions/', ShowAll.as_view(), name='all' ),
    path('questions/vote/<pk>',ShowDetail.as_view(),name="show_detail" ),
    path('questions/<int:question_id>/', show_detail, name='detail'),

]

site_/vote/models.py
from django.db.models.fields.related import OneToOneField
from site_.settings import TIME_ZONE
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    q_text = models.CharField(max_length=100)
    q_date = models.DateField(default=timezone.now)

    def __str__(self) -> str:
        return self.q_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    c_text = models.CharField(max_length = 100)
    vote = models.IntegerField(default=0)
    def __str__(self) -> str:
        return self.c_text

site_/vote/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse, get_list_or_404, get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
# Create your views here.
from . models import Question, Choice
def index_vote(request, *args, **kwargs):
    return HttpResponse("hello")

class ShowAll(ListView):
    model = Question
    context_object_name="all_q"
    template_name = "show_all.html"

# def all_questions(request, *args, **kwargs):

#     all_questions = Question.objects.all()
#     context = {
#         "all_q": all_questions
#     }
#     return render(request, 'show_all.html', context )

class ShowDetail(DetailView):
    template_name = 'show_detail.html'
    context_object_name = "question"
    model = Question
    
        


def show_detail(request, question_id):
    if request.method == "GET":
        q = Question.objects.get(id=question_id)
        context = {
            "question":q
        }
        return render(request, 'show_detail.html',context)
    
    else:
        q = Question.objects.get(id=question_id)

        try:
            choice_selected = q.choice_set.get(id = request.POST["choice"])
        except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
            return render(request, 'show_detail.html', {
                'question': q,
                'error_message': "You didn't select a choice.",
            })
        else:
            choice_selected.vote += 1
            choice_selected.save()
        return HttpResponse("submited")

site_/vote/templates/show_all.html
{% for question in all_q %}
<li>
    <a href="{% url 'vote:show_detail' question.id %}">
        {{question.q_text}}
    </a>
</li>
{% endfor %}

site_/vote/templates/show_detail.html
{{question.q_text}}


<form method="POST", action="{% url 'vote:detail' question.id %}">
    {% csrf_token %}
    <fieldset>
        <h1>{{question.q_text}}</h1>

        {% if error_message %}<p>{{error_message}}</p>
        {% endif %}

        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" value="{{choice.id}}" id="{{foorloop.counter}}">
        <label for="choice{{ forloop.counter }}">{{ choice.c_text}}{{choice.id}}</label><br>
        

{% endfor %}
<input type="submit" value="submit">
    </fieldset>
</form>